import {
    HomeIcon,
    ChatBubbleLeftRightIcon,
    ChatBubbleLeftEllipsisIcon,
    UsersIcon,
    Cog6ToothIcon,
    BellIcon,
    ChartBarIcon,
    CalendarDaysIcon,
    LinkIcon,
    BanknotesIcon,
    DocumentDuplicateIcon,
  } from "@heroicons/react/24/outline";
  
  export const navConfig = {
    palette: {
      mainGradient: "from-blue-500 via-violet-500 to-indigo-600",
      textActive: "text-white",
      textInactive: "text-gray-500 dark:text-gray-300",
      bgSidebar: "bg-white dark:bg-gray-950",
      bgBottomNav: "bg-white/90 dark:bg-gray-950/80 backdrop-blur",
      borderSidebar: "border-r border-gray-200 dark:border-gray-800",
    },
    items: [
      {
        id: "dashboard",
        path: "/tenant/dashboard",
        icon: HomeIcon,
        label: { en: "Dashboard", ar: "الرئيسية" },
        roles: ["tenant"],
      },
      {
        id: "messages",
        path: "/tenant/messages",
        icon: ChatBubbleLeftEllipsisIcon,
        label: { en: "Messages", ar: "المحادثات" },
        roles: ["tenant"],
      },
      {
        id: "bookings",
        path: "/tenant/bookings",
        icon: CalendarDaysIcon,
        label: { en: "Bookings", ar: "الحجوزات" },
        roles: ["tenant"],
      },
      {
        id: "campaigns",
        path: "/tenant/campaigns",
        icon: ChatBubbleLeftRightIcon,
        label: { en: "Campaigns", ar: "الحملات" },
        roles: ["tenant"],
      },
      {
        id: "customers",
        path: "/tenant/customers",
        icon: UsersIcon,
        label: { en: "Customers", ar: "العملاء" },
        roles: ["tenant"],
      },
      {
        id: "team",
        path: "/tenant/team",
        icon: UsersIcon,
        label: { en: "Team", ar: "الفريق" },
        roles: ["tenant"],
      },
      {
        id: "integration",
        path: "/tenant/integration",
        icon: LinkIcon,
        label: { en: "Integration", ar: "الربط" },
        roles: ["tenant"],
      },
      {
        id: "topUp",
        path: "/tenant/top-up",
        icon: BanknotesIcon,
        label: { en: "Top Up", ar: "شحن الرصيد" },
        roles: ["tenant"],
      },
      {
        id: "notificationSettings",
        path: "/tenant/notification-settings",
        icon: BellIcon,
        label: { en: "Notifications", ar: "الإشعارات" },
        roles: ["tenant"],
      },
      {
        id: "reports",
        path: "/tenant/reports",
        icon: DocumentDuplicateIcon,
        label: { en: "Reports", ar: "التقارير" },
        roles: ["tenant"],
      },
      {
        id: "adminDashboard",
        path: "/admin/dashboard",
        icon: HomeIcon,
        label: { en: "Dashboard", ar: "لوحة التحكم" },
        roles: ["admin"],
      },
      {
        id: "managePages",
        path: "/admin/manage-pages",
        icon: DocumentDuplicateIcon,
        label: { en: "Manage Pages", ar: "إدارة الصفحات" },
        roles: ["admin"],
      },
      {
        id: "manageTenants",
        path: "/admin/manage-tenants",
        icon: UsersIcon,
        label: { en: "Manage Tenants", ar: "إدارة المستأجرين" },
        roles: ["admin"],
      },
    ],
  };